version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Oslo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: com.google.firebase:firebase-bom
    versions:
    - 26.3.0
    - 26.4.0
    - 26.5.0
    - 26.6.0
    - 26.7.0
    - 26.8.0
    - 27.0.0
  - dependency-name: androidx.core:core-ktx
    versions:
    - 1.5.0-beta01
    - 1.5.0-beta02
    - 1.5.0-beta03
    - 1.6.0-alpha01
  - dependency-name: androidx.recyclerview:recyclerview
    versions:
    - 1.2.0-beta01
    - 1.2.0-beta02
    - 1.2.0-rc01
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.google.android.material:material
    versions:
    - 1.3.0
    - 1.3.0-rc01
    - 1.4.0-alpha01
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: androidx.constraintlayout:constraintlayout
    versions:
    - 2.1.0-alpha2
  - dependency-name: junit:junit
    versions:
    - 4.13.1
